{
 "title": "Biogen Dashboard 1",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Biogen Dashboard",
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 3, "y": 0 },
   "content": "<center><h2>System Overview<h2></center>\n\n\n\n"
  },
  {
   "title": "Hospitals Disconnected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "svc_disconnected_hospitals" }
   ]
  },
  {
   "title": "ERROR QUEUE",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "svc_percentage_of_success" }
   ]
  },
  { "title": "Last Message Received", "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 } },
  {
   "title": "INSIGHTS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "svc_insights" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 4 },
   "content": "\n# DICOM SERVICE\n\nSERVICE IS RUNNING\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 4 },
   "content": "\n# INTEGRATION SERVICES\nSERVICE IS RUNNING\n\n\n\n"
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "svc_cpu_usage" }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "svc_cpu_usage" }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "svc_memory" }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "svc_memory" }
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "svc_disk_space" }
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "svc_disk_space" }
   ]
  },
  {
   "title": "Hospitals",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "format": "timeseries_to_rows",
   "targets": [
    { "target": "[object Object]", "type": "table" }
   ]
  }
 ]
}