{
 "title": "Biogen Dashboard 2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "content": "# Hospital is Connected\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 8, "y": 0 },
   "content": "Error Queue: 5 Erros<p align=\"right\"><a href=\"https://www.google.com/\">LINK</a></p>\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "content": "# Last Message Recieved: 30th August 2019\n\n\n\n"
  },
  {
   "title": "ERROR INSIGHTS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "svc_error_insights" },
    { "expr": "svc_error_insights_total" }
   ]
  },
  {
   "title": "PERCENTAGE OF SUCCESS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "svc_percentage_of_success" }
   ]
  },
  {
   "title": "MESSAGE TYPES",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "svc_message_types" }
   ]
  },
  {
   "title": "PATIENT CONSENT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "svc_patient_consent" }
   ]
  }
 ]
}